app:
  debug: true
database:
  path: data/gestion_locative.db
export:
  backup_directory: data/backups
receipts:
  company_name: Magic House
  company_names:
  - Magic House
  - Mohamed Fayala
  signature_path: ''
  signatures:
  - name: mohamed
    path: C:/Users/LENOVO/Desktop/papiers/signature.jpg
