app:
  debug: true
database:
  path: D:\code\locations\data\gestion_locative.db
export:
  backup_directory: D:\code\locations\data\backups
receipts:
  company_name: Magic House
  signature_path: C:/Users/LENOVO/Desktop/papiers/signature.jpg
